// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "cb728bdc-8ab6-4ef3-ab54-990875b4b640");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1773926482);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1773926481);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "f609a2f1-82f0-4ab8-a462-b0fd5d67845a");
user_pref("browser.contextual-services.contextId.rotation-in-days", 3);
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1773926479);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 159);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-v2-copy:treatment-a-callout-badge");
user_pref("browser.ml.chat.page", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.publisherFavicon.enabled", true);
user_pref("browser.newtabpage.activity-stream.discoverystream.refinedCardsLayout.enabled", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8c5c993c-d3db-4939-9812-e24a5d08a3ca}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.profiles.created", true);
user_pref("browser.profiles.enabled", true);
user_pref("browser.profiles.profile-name.updated", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1773926479);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1773926484272");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1773948084272");
user_pref("browser.search.region", "RU");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1773926479");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1773926479);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1773926480);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.dataCollection.enabled", false);
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("captchadetection.lastSubmission", 1773926);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "fa74dd32-beed-4144-90c4-5f5222d897c9");
user_pref("datareporting.dau.cachedUsageProfileID", "8ae42a86-94fa-4d8c-b1c1-b4a7bba5d4eb");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1773926433708");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "143.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "RU");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "9a07f2409fdd4cb9b0dbdf8b6df14432");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1773926479);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250930222537");
user_pref("extensions.lastAppVersion", "143.0.3");
user_pref("extensions.lastPlatformVersion", "143.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ee18977f-123b-49e5-99e1-e150a01c003f\",\"ipp-activator@mozilla.com\":\"0f8a4ad6-dc16-4d4a-9408-1f3d57d301c9\",\"pictureinpicture@mozilla.org\":\"e103f4dd-8775-4c5e-9d1d-5f7d9bcc9500\",\"addons-search-detection@mozilla.com\":\"3f3836e2-439b-4f12-8854-e0a891ea96c7\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"e9291210-6d5f-4bee-8a6c-f5bbe7651ef3\",\"default-theme@mozilla.org\":\"16b22a98-7ce9-45e9-8051-457506e10bc8\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 2);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "f7fc604a-55c9-40ae-b278-415b9723180a");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.revamp.defaultLauncherVisible", false);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("toolkit.profiles.storeID", "be7b006e");
user_pref("toolkit.startup.last_success", 1773926477);
user_pref("toolkit.telemetry.cachedClientID", "f3913197-eac6-4163-9d64-d81586e46d77");
user_pref("toolkit.telemetry.cachedProfileGroupID", "47db8347-0c7c-42a4-9b69-e754076643f0");
user_pref("toolkit.telemetry.previousBuildID", "20250930222537");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
